# Generated by Django 3.0.2 on 2020-02-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='default_photo_profile.jpg', upload_to='users/%y/%m/%d/'),
        ),
    ]
