# Generated by Django 3.0.2 on 2020-02-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200209_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='static/default_photo_profile.jpg', upload_to='users/%y/%m/%d/'),
        ),
    ]
